### ISSUE TITLE
Spritesheet generator as an option?

### ISSUE THREAD

**Issue by raphaelluchini** [Swiip/generator-gulp-angular#154]
What do you think include a option for a gulp task generate a spritesheet using only gulp or sass as a gulp task? In this case we'd use src/assets/compiled-images and src/assets/images(non compiled). In some cases you don't want to generate a spritesheet for all your images, for example a facebook image share. And in the dist folder we could the sabe js naming style(spritesheet-e2cdf34.png).

**Comment by zckrs** [comment]
Nice idea but that should be a recipe like `docs/recipes/create-spritesheet.md`.

@raphaelluchini  can you create this recipes ?

**Comment by raphaelluchini** [comment]
Yes @zckrs , for sure, but there is a reason to not be included as an option?

**Comment by zckrs** [comment]
Yes it is very specific. For a concrete option we should change the CSS of the sample application and the controller who list technologies used

**Comment by rosscdh** [comment]
Hi there, where does one find the recipes/docs?

Trying to customise the mdThemeProvider and mdIconProvider with material-design-icons but so far no joy. seems to be specific to the generator.

**Comment by intellix** [comment]
Another, which I'm using: https://github.com/aslansky/css-sprite

**Comment by zckrs** [comment]
This issue is a nice feature/enhancement but we (Swiip and me) don't have time to implement this for the moment.
Our first priority is stabilized functionality already present in the generator for the purpose of releasing v1.0.0

For clarity in issues I will close the issue and marks it as "good-but-no-time".
Any good contributions to resolve this matter is appreciated and merged.

Otherwise we will reopen the issue after the v1.0.0
