### ISSUE TITLE
Replace JSHint with ESLint

### ISSUE THREAD

**Issue by tlvince** [Swiip/generator-gulp-angular#168]
[ESLint](http://eslint.org) is like JSHint++; it has pluggable rulesets, is robust and is more actively maintained. Worth considering to be included, if not replacing JSHint entirely.

**Comment by paglias** [comment]
+1

**Comment by zckrs** [comment]
This issue is a nice feature/enhancement but we (Swiip and me) don't have time to implement this for the moment.
Our first priority is stabilized functionality already present in the generator for the purpose of releasing v1.0.0

For clarity in issues I will close the issue and marks it as "good-but-no-time".
Any good contributions to resolve this matter is appreciated and merged.

Otherwise we will reopen the issue after the v1.0.0

**Comment by al-the-x** [comment]
Interested in PRs to add this feature?

**Comment by Swiip** [comment]
Yep, a lot!

I'm seriously reconcidering switching to ESLint before the 1.0 release. We had a failed experience trying to use JSCS (which is covered by ESLint) and I also want to add https://www.npmjs.com/package/eslint-plugin-angular which is great...

**Comment by al-the-x** [comment]
Yeah, I went through the history on JSCS. Sorry that didn't work out, but
ESLint is much better as a successor to JSLint. The gulp-webapp project
recently switched, and I'm happy to submit a PR.

**Comment by zckrs** [comment]
v1.0.0-rc1 released on NPM.

[How to update my project?](https://github.com/Swiip/generator-gulp-angular/blob/master/docs/recipes/upgrade-my-current-project.md)
