### ISSUE TITLE
Nightwatch.js Intergration or Replacement for Protractor

### ISSUE THREAD

**Issue by jeffscottward** [Swiip/generator-gulp-angular#17]
Firstly... I LOVE THIS.

Secondly... I think Nightwatch.js would be a perfect fit. Pipe through the UI with CSS selectors and assert tests along the way. Super fun. I wrote a script recently to buy bitcoin, it was cool :).

Hopefully the site will be up soon. 
Here is a cached copy in the meantime.
http://webcache.googleusercontent.com/search?q=cache:http://nightwatchjs.org/

**Comment by zckrs** [comment]
This issue is a nice feature/enhancement but we (Swiip and me) don't have time to implement this for the moment.
Our first priority is stabilized functionality already present in the generator for the purpose of releasing v1.0.0

For clarity in issues I will close the issue and marks it as "good-but-no-time".
Any good contributions to resolve this matter is appreciated and merged.

Otherwise we will reopen the issue after the v1.0.0
