### ISSUE TITLE
Unhandled error event at index.css.map

### ISSUE THREAD

**Issue by climboid** [Swiip/generator-gulp-angular#186]
I keep running into this issue while executing `grulp serve`

```
[07:28:53] gulp-ruby-sass: write vendor.css
      write vendor.css.map

events.js:72
        throw er; // Unhandled 'error' event
              ^
/Users/climboid/Development/test/index.css.map:3:1: Unknown word
"version": 3,
"mappings": "AAAA,YAAa;EACX,MAAM,EAAE,OAAO;EACf,UAAU,EAAE,IAAI;EAChB,KAAK,EAAE,IAAI;EACX,OAAO,EAAE,OAAO;;;AAGlB,UAAW;EACT,MAAM,EAAE,KAAK;;AAEb,yBAAe;EACb,KAAK,EAAE,IAAI",
^
"sources": ["../index.scss"],
```

Not sure exactly what is causing it. Any help is much appreciated

**Comment by xmlilley** [comment]
This issue seems to remain in latest release, and I see it in a fresh demo project I installed using latest download of the generator. I know that the community is waiting on updates to other tools to permanently resolve the sourcemaps issue, but perhaps sourcemaps should be turned off by default until that happens? 

Otherwise anyone using rubysass is going to start out broken, and if they even understand what's going on, they're going to spend a good bit of time troubleshooting (yes, I did :-) before figuring out where the problem is.
