### ISSUE TITLE
Translation feature

### ISSUE THREAD

**Issue by Toilal** [Swiip/generator-gulp-angular#231]
Do you think it's a good idea to add translation feature ?

I'm using [angular-gettext](https://github.com/rubenv/angular-gettext), so i could implement this one in a PR if you think it make sense to be included.

[angular-translate](https://github.com/angular-translate/angular-translate) seems more popular, but I need to stick on GNU gettext standard files.

**Comment by csablons** [comment]
I think it's a pretty useful idea :)

**Comment by Swiip** [comment]
It could be interesting as a feature. As there is enough options already, I think it will be in the new advanced mode.

angular-translate is very popular, I thought it was pluggable enough to inject some sort of interpreter for the type of files you need.

If it's a new option, I think angular-translate (among others if you want) must be addressed and the initial templates has to be "internationalized"

**Comment by Toilal** [comment]
Ok, so i'll have a look to angular-translate and see if it can generates `po`/`pot` files.

**Comment by JG-CMASS** [comment]
While I agree a good localization feature is badly needed just be aware that these two client side solutions (gettext / translate) have some inherent drawbacks; namely performance http://blog.altoros.com/speed-up-i18n-in-angularjs.html, FOUT (Flash of Un-styled Content) and SEO index scoring. Additionally, referencing individual keys instead of a cascading reference (eg. errors.* is a bit of a pain)

For lighter applications this may be a reasonable trade-off however for large applications I would suggest a third, build step, alternative.

What we did on a recent project (after evaluating gettext / translate) was to use Gulp Template https://github.com/sindresorhus/gulp-template as a pre-processor for translation strings which pretty much solves the above issues. Also, given that it is a complete lo_dash wrapper for build time this gave us additional power we wouldn't other wise had above and beyond simply translation.

That being said, it does come with drawbacks itself:
1. You need to generate multiple files for each language
2. You can't change language on the fly as you could the client side solution(s)
3. The syntax <%= namespace.key %> can cause issues for various validators included with the most popular IDE's
4. It currently can't make use of the po/pot file approach which may be necessary depending on the translation team's requirements.

Anyways, the intent of this is not to advocate against a gettext / translate option but perhaps you might consider a build time solution to localization at some point in the future as well.

**Comment by xmlilley** [comment]
My humble $0.02: I'd love to see a well-packaged build-time solution too, preferably with the ability to generate compiled templates for *all* supported languages, then toggle amongst them at runtime. But I'd think somebody would want to hammer out the details of generalizing that into a standalone module first, before trying to fold it into a generator like this one.

(And... I definitely agree that I18n is probably best handled in the advanced options. I use it often myself, but I don't think it's quite universal enough a concern to be a default item for most devs.)

(And... thanks guys, for an awesome tool! This is really a very, very well-done project that I'm going to get a lot of use out of.)

**Comment by Swiip** [comment]
Deliver a packaged solution for i18n at compile time is great idea that I'll store in the todo :)

Yet, I think that i18n can exist as an simpler option waiting for the ultimate solution to be ready.

Finally, as we discuss of the stabilization of the 1.0 version, I think it's not the time to open such a big change.

**Comment by Toilal** [comment]
:+1: This idea is great :)

I'll be ok to spend time to implement it after 1.0 release, and i'll add it now manually to my current project.

**Comment by zckrs** [comment]
This issue is a nice feature/enhancement but we (Swiip and me) don't have time to implement this for the moment.
Our first priority is stabilized functionality already present in the generator for the purpose of releasing v1.0.0

For clarity in issues I will close the issue and marks it as "good-but-no-time".
Any good contributions to resolve this matter is appreciated and merged.

Otherwise we will reopen the issue after the v1.0.0

**Comment by intellix** [comment]
Doesn't 1.4 come with i18n translation support out of the box or as an official module or so. I'm using angular-gettext at the moment though, great to see it here. the creator of angular-gettext also created extraction and compilation tasks for grunt/gulp as well
