### ISSUE TITLE
Emit coffee specs

### ISSUE THREAD

**Issue by chakatodd** [Swiip/generator-gulp-angular#253]
When choosing coffeescript during "yo gulp-angular", if the users chooses coffeescript then emit tests in coffee too.

**Comment by Swiip** [comment]
We know this would be better but I don't know if it's possible.

Indeed, coffee specs are only one step, there is also the gulpfiles in coffee, the specs in typescript, es6... It's so much of work and after that, we have to maintain all of it...

**Comment by Toilal** [comment]
@Swiip I think even if it's a bit work, specs should really be written in the langage choosen by the user, because those generated files serves as template for writing other specs for others components and features.

I'm agree it's not required and really to much work for gulp files, but specs files should be translated too.

As i'm near of those concerns with my current PR, i could translate those specs files in a later PR, as i'm now more confortable with supported javascript preprocessors.

**Comment by Swiip** [comment]
gulpfiles will clearly never be translated.

But I agree, specs files should be. But watch out, it can be not obvious to process tests files before giving them to Karma.

**Comment by RomFouq** [comment]
This is just an idea, but perhaps it could be possible to use js2coffee, to auto-compile js files to coffee. This avoids the pain of manually translating all these js files but also of maintaining them, since they could be automatically generated from js files.

**Comment by Swiip** [comment]
We already talked about js2coffee for the sources. I didn't like generated code like that and in anyway, this doesn't work for es6 or ts so... no. We'll do it one day, but for real.

**Comment by zckrs** [comment]
https://github.com/Swiip/generator-gulp-angular/pull/598/ merged

If you choose CoffeScript you get a sample test `main.controller.spec.coffee`

Appreciated contribution to improve coverage test.
