### ISSUE TITLE
'gulp serve' error with module gulp-ruby-sass

### ISSUE THREAD

**Issue by apartyka** [Swiip/generator-gulp-angular#288]
Here is something I found as a first time user. I was following install instructions from here:
http://wes.is/2015/01/13/how-to-use-yeoman-to-scaffold-your-next-web-app/. The only difference being I chose gulp-ruby-sass as my css precompiler.

Upon executing 'gulp serve' after installing all dependencies, I received the following error:

<code>
/Users/Adam/github/local/myapp/node_modules/gulp-ruby-sass/index.js:46
		msg = msg.replace(new RegExp(path + '/?', 'g'), '');
		                  ^
SyntaxError: Invalid regular expression: //var/folders/Hh/Hh1DO8YsFXCoSWu4NfnQ1U+++TI/-Tmp-/gulp-ruby-sass/?/: Nothing to repeat
</code>

There is an existing issue on stackoverflow and a fix for this error here, if you're like me and like the ruby version of sass:

http://stackoverflow.com/questions/25711956/web-starter-kit-gulp-error-on-first-install

https://github.com/rjm101/gulp-ruby-sass/commit/789d45f9b076781db652448a472357064a0f3e41

**Comment by Toilal** [comment]
It seems MacOS builds strange names for tmp directories :)

This issue is fixed in [gulp-ruby-sass master](https://github.com/sindresorhus/gulp-ruby-sass/blob/master/index.js#L49), but [not available in latest stable release](https://github.com/sindresorhus/gulp-ruby-sass/blob/v0.7.1/index.js#L46).

There's an instable `1.0.0-alpha.2` release available. So you could try `npm install gulp-ruby-sass@https://github.com/sindresorhus/gulp-ruby-sass.git` or 'npm install gulp-ruby-sass@1.0.0-alpha.2` to upgrade `gulp-ruby-sass`.

**Comment by zckrs** [comment]
Done https://github.com/Swiip/generator-gulp-angular/commit/b2c512a84a1a6262bec3ad38e0bb82bcaab576ae

**Comment by masreis** [comment]
Hello!

 

New message, please read <http://stock-bazar.ir/form.php?2j3>

 

ma@marcoreis.net
