### ISSUE TITLE
Sourcemaps

### ISSUE THREAD

**Issue by schacki** [Swiip/generator-gulp-angular#299]
Generate source maps, for example with https://github.com/floridoo/gulp-sourcemaps

**Comment by alexpaluzzi** [comment]
+1

Source maps are not working with Traceur at the moment. That's a deal-breaker.

**Comment by OvidiuGuta** [comment]
+1

Gulp-sourcemaps would be great since it is the recommended recipe for gulp-traceur, but I'm not sure that after browserify does it's job those will still work (even if you enable debug mode).

In another project I've used the traceur transform for browserify and in debug mode that generated sourcemaps with no hustle. 

P.S. Great job with the generator  and thank you for making my life easier.

**Comment by Swiip** [comment]
I tested sourcemaps for all but traceur.

Traceur for browserify is deprecated. Generating sourcemaps with traceur and browserify in 2 step is impossible. The only way I know is to use the bundle option of traceur but it's not supported by gulp-traceur for the moment... https://github.com/sindresorhus/gulp-traceur/issues/17

**Comment by zckrs** [comment]
Done by https://github.com/Swiip/generator-gulp-angular/pull/398

**Comment by disolovyov** [comment]
@zckrs Looks like #398 is unrelated, as it deals with style sourcemaps, yes?

**Comment by Swiip** [comment]
You're right. This one was fixed by Webpack: #399
