### ISSUE TITLE
request: add gulp angular htmlify

### ISSUE THREAD

**Issue by okadesign** [Swiip/generator-gulp-angular#311]
would it be possible ?

**Comment by Swiip** [comment]
To be honest, you're the first asking for this. In fact, I didn't know it exists.

**Comment by mohsen1** [comment]
I vote no for this. Many people don't care about valid HTML anymore.

**Comment by Swiip** [comment]
Yeah, i'm not sure many people care anymore.

But it could be an advanced option if there is the need.

**Comment by zckrs** [comment]
I like this song :+1:

**Comment by blackfyre** [comment]
:+1:

**Comment by zckrs** [comment]
This issue is a nice feature/enhancement but we (Swiip and me) don't have time to implement this for the moment.
Our first priority is stabilized functionality already present in the generator for the purpose of releasing v1.0.0

For clarity in issues I will close the issue and marks it as "good-but-no-time".
Any good contributions to resolve this matter is appreciated and merged.

Otherwise we will reopen the issue after the v1.0.0
