### ISSUE TITLE
How to add fontawesome

### ISSUE THREAD

**Issue by domoritz** [Swiip/generator-gulp-angular#337]
I'm struggling with getting fontawesome to work with the generated gulp.

I tried to copy the files with a new gulp task in `build.js`

```js
gulp.task('fontawesome', function() { 
  return gulp.src('bower_components/fontawesome/fonts/*.*') 
    .pipe(gulp.dest(paths.dist + '/bower_components/fontawesome/fonts/'));
});
```

And added the following to the scss file.

```scss
$fa-font-path: "../../bower_components/fontawesome/fonts";
@import "../../bower_components/fontawesome/scss/font-awesome.scss";
```

This works fine for development but breaks in dist (because the relative location of the css file changes. How do I set up the paths correctly? Can I use the `fonts` task?

Or in other words. How do I make sure that relative paths to fonts in scss don't break in production?

**Comment by martyla** [comment]
I did something like:
```sh
gulp.task('html', ['inject', 'partials'], function () {
...
return gulp.src(paths.tmp + '/serve/*.html')
  ...
  .pipe($.replace('../bower_components/bootstrap-sass-official/assets/fonts/bootstrap', 'fonts'))
  .pipe($.replace('../bower_components/fontawesome/fonts', 'fonts'))
  ...
```

As the fonts should be automatically copied to `dist/fonts`.

Also to get the bootstraph glyphicons working for `gulp serve:dist` (as above) I had to replace:
```sh
.pipe($.replace('../bootstrap-sass-official/assets/fonts/bootstrap', 'fonts'))`
```
with:
```sh
.pipe($.replace('../bower_components/bootstrap-sass-official/assets/fonts/bootstrap', 'fonts'))`
```

Which might be an issue with the generator or I'm just doing something wrong ...

**Comment by Swiip** [comment]
The current font task only copy fonts declared in bower packages. It's the case for bootstrap, I don't know for fontawesome. After that we put the font in a specific directory.

Secondly, we have to replace the font path as you seen to point the right directory in the dist directory structure.

First of all, have you your font files in the dist directory ?

**Comment by martyla** [comment]
Also my bad in my previous comment. I was using an different version of font awesome that didn't have the fonts declared in `bower.json`. In the current version I didn't need to declare anything extra and it magically added everything from `./bower_components/font-awesome`.

One thing though, is the new font awesome causes an error if the .woff2 font isn't copied to the `./dist/fonts` and I had to add it manually:
```
gulp.task('fonts', function () {
  return gulp.src($.mainBowerFiles())
    .pipe($.filter('**/*.{otf,eot,svg,ttf,woff,woff2}'))
...
```

**Comment by Swiip** [comment]
yeah, woff2 has been added recently to the scripts and not released yet i think

**Comment by domoritz** [comment]
It looks like $.mainBowerFiles() does not handle wildcards (https://github.com/FortAwesome/Font-Awesome/blob/master/bower.json#L12) correctly. At least I don't see any of the font files when I run

```js
console.log($.mainBowerFiles());
```

**Comment by domoritz** [comment]
Awesome. It's all working now. The scss import looks like

```scss
$fa-font-path: "../../bower_components/fontawesome/fonts";
@import "../../bower_components/fontawesome/scss/font-awesome.scss";
```

and I had to add a step to the `html` pipeline

```js
.pipe($.replace('../../bower_components/fontawesome/fonts', '../fonts'))
```

**Comment by bsides** [comment]
@domoritz I'm sorry, but how did you achieve to get it working in development? Could you post the complete steps? Thank you

**Comment by domoritz** [comment]
Our project is here. https://github.com/uwdata/polestar

**Comment by Hesesses** [comment]
I'm having the same problem, fontawesome works with serve but not included in dist folder after build

**Comment by claboran** [comment]
To get it working for serve:dist a workaround could be found at issue #637.
Best regards,
Chris

**Comment by disharmonized** [comment]
Just in case, for LESS solution will be:
* index.less:
```
@import "../../bower_components/font-awesome/less/font-awesome.less";
$fa-font-path: "../../bower_components/font-awesome/fonts";
```
* gulp/build.js
```
.pipe($.replace('../../bower_components/font-awesome/fonts', '../fonts/'))
```

**Comment by adriangordon1231** [comment]
+1

**Comment by dgoncalves1** [comment]
@claboran i tried that solution but still not sure how to do with font-awesome, how am i supposed to do it? is there any fix or do i have to manually copy the font awesome folder?

**Comment by danieldiazastudillo** [comment]
@dgoncalves1 I've been struggling with this and my solution was:

1. Make the SCSS imports:
    $fa-font-path: "../../bower_components/fontawesome/fonts";
    @import "../../bower_components/fontawesome/scss/font-awesome.scss";

With this step you'll see FA icons in dev mode (src).

2.In **gulp/build.js** there's a task called `html`, you must add this pipe:
    .pipe($.replace('../../bower_components/fontawesome/fonts', '../fonts'))

So far, it's the solution proposed in **recipes** and everything works great in dev mode BUT when you run the BUILD task it won't copy FA fonts to the **dist/fonts** folder because they must be declared in your `bower.json` as an **override** like this:

    "font-awesome": {
          "main": [
            "scss/font-awesome.scss",
            "fonts/*"
          ]
    }

I used a wildcard, inside the file Bootstrap fonts are declared explicitly, that's your choice. Hope this helps.

**Comment by claboran** [comment]
@dgoncalves1 : Did it work now for serve:dist?

**Comment by j0hnsmith** [comment]
It took me a while to get Font Awesome working so I'm adding what I did (I think things have changed since some comments above were written).

```
bower install --save fontawesome  // gives me "font-awesome": "fontawesome#~4.4.0"
```

#### `serve`
In `index.less`, only update the `@fa-font-path` variable (less) or `$fa-font-path` (I guess) for sass, no manual imports are necessary.
```
...
// endbower
@fa-font-path: "../../bower_components/font-awesome/fonts";
...
```

#### `serve:dist` 
Modify the `gulp fonts` task to copy font files from `bower_components` (as suggested in https://github.com/Swiip/generator-gulp-angular/issues/849#issuecomment-149094381), and also modify the `gulp html` task to fix the path to the fonts.

```
gulp.task('html', ['inject', 'partials'], function () {
...
    .pipe($.replace('../../bower_components/font-awesome/fonts', '../fonts/'))
    .pipe(gulp.dest(path.join(conf.paths.dist, '/')))
...
```

**Comment by adriangordon1231** [comment]
Why not just use the cdn:  https://www.bootstrapcdn.com/fontawesome/

**Comment by dgoncalves1** [comment]
@claboran haven't had the time to do it, as soon as I can I'll provide feedback.

**Comment by mdentinho** [comment]
Hey guys, 

I've been dealing with an issue that might be related to this. I'm using the latest release of the generator that already includes the `.pipe($.replace('../../bower_components/font-awesome/fonts', '../fonts/'))` line in the `html` task of the `build.js` file.

When running both from `source` or from `dist`, the `ttf`, `woff` and `woff2` Font Awesome font files retrieve a 404 error on all browsers and no other font type (`eot` and `svg`) is loaded. The weird thing is that the icons are shown in all browsers but Firefox.

When building the project I can't find the fonts in the `/dist/fonts/` folder which makes me wonder how can the broswers (but Firefox) show the icons if the fonts are not even there.

I found some known issues with Firefox that make the icons not appear in it, but they are all related to CDN Access Rights, but since I'm not using any CDN, I thought that I should ask here first.

I hope someone can help.
Cheers!

**Comment by poliveira89** [comment]
I have done what @danieldiazastudillo told but for LESS, and did not worked for me.

I have added this to my `index.less` between the parts that will be update with gulp tasks:
```LESS
// bower:less
// endbower

[...]

@fa-font-path: '../../bower_components/font-awesome/fonts';
@import '../../bower_components/font-awesome/less/font-awesome.less';

[...]

// injector
// endinjector
```

And then on `html` gulp task I added into the pipe right after the line on bootstrap fonts:
```js
    .pipe($.replace('../../bower_components/bootstrap/fonts/', '../fonts/'))
    .pipe($.replace('../../bower_components/font-awesome/fonts/', '../fonts/'))
```

**Comment by olimungo** [comment]
Instead of modifying any file in the gulp build, I added the following section to **my** project's bower.json:
``
  "overrides": {
    "font-awesome": {
      "main": "css/font-awesome.css"
    }
```

**Comment by poliveira89** [comment]
@olimungo you **ONLY** edited the `bower.json`?

**Comment by olimungo** [comment]
@poliveira89 Yes, that's what I like in this solution. And I used Sass with Node.

**Comment by poliveira89** [comment]
@olimungo but for what I have been looking for on "fonts" task with `gulp-debug` the problem is that the fonts files is not delivered by `$.mainBowerFiles()` so when the stream reaches the `.pipe($.filter('**/*.{eot,svg,ttf,woff,woff2}'))` it's handling 0(zero) files :/

But if I "override" it like you say, in theory the problem will be the same... :/

**Comment by wonsikin** [comment]
@danieldiazastudillo Thanks. Now my project works well after running `build` task.

**Comment by alaksandarjesus** [comment]
Its not working my dist folder. My console is throwing this error.

http://localhost:3000/bower_components/font-awesome/fonts/fontawesome-webfont.woff2?v=4.4.0 Failed to load resource: the server responded with a status of 404 (Not Found)

I added in gulp/build.js
    .pipe($.replace('../../bower_components/fontawesome/fonts', '../fonts'))

In index.scss
$fa-font-path: '../../bower_components/font-awesome/fonts';
@import '../../bower_components/font-awesome/scss/font-awesome.scss';

Its working fine in serve but not in build

**Comment by gablabelle** [comment]
The recipe seems incomplete because when you build to dist using the the `gulp` command, the font-awesome icon files from its bower package will not be copied to the folder: dist/fonts/

You will need to modify the bower.json of your project for the files to be copied:

```
...
  "devDependencies": {
    "angular-mocks": "~1.4.2"
  },  
 "overrides": {
    "bootstrap-sass": {
      "main": [
        "assets/stylesheets/_bootstrap.scss",
        "assets/fonts/bootstrap/glyphicons-halflings-regular.eot",
        "assets/fonts/bootstrap/glyphicons-halflings-regular.svg",
        "assets/fonts/bootstrap/glyphicons-halflings-regular.ttf",
        "assets/fonts/bootstrap/glyphicons-halflings-regular.woff",
        "assets/fonts/bootstrap/glyphicons-halflings-regular.woff2"
      ]
    },
    "font-awesome": {
      "main": [
        "scss/font-awesome.scss",
        "fonts/fontawesome-webfont.eot",
        "fonts/fontawesome-webfont.svg",
        "fonts/fontawesome-webfont.ttf",
        "fonts/fontawesome-webfont.woff",
        "fonts/fontawesome-webfont.woff2"
      ]
    }
  }
...
```

Then, you will need to modify the gulp/build.js (lines 53 and 54 in the 'html' task) file to make sure that the path to these font-awesome font files is correct:

```
...
.pipe($.replace('../../bower_components/bootstrap-sass/assets/fonts/bootstrap/', '../fonts/'))
.pipe($.replace('../../bower_components/font-awesome/fonts', '../fonts'))
...
```

And finally, you will need to specify the $fa-font-path in you scss file (ie. index.scss):

```
...
// Bootstrap icon font
$icon-font-path: "../../bower_components/bootstrap-sass/assets/fonts/bootstrap/";

// Font awesome fonts
$fa-font-path: "../../bower_components/font-awesome/fonts";
...
```

`gulp serve` : fonts are OK
`gulp` : fonts are OK (build in dist)

Hope it helps and that I didn't forget anything. ;-)

**Comment by codeofsumit** [comment]
We installed font awesome via this shim repository:

https://github.com/components/font-awesome

and it works just fine. Probably because their bower.json correctly lists all the font files.

**Comment by Santino-Wu** [comment]
I had the same issue, and i fixed it by @gablabelle 's solution, thanks!

**Comment by MZellhofer** [comment]
Same for me - @gablabelle 's solution works, many thanks! Just something that took me quite a while, even though it was pretty obvious: make sure to do the replacements in `build.js` after

```
...
    .pipe(cssFilter.restore)
...
```

**Comment by codeofsumit** [comment]
just tried it again without the shim and yes, the recipe is incomplete, @gablabelle version works!

**Comment by runmael** [comment]
@MZellhofer why do we need to put it after `cssFilter.restore` to work correctly? It actually works when I do that, but I cannot grasp why...

**Comment by xkeshav** [comment]
moving down the font awesome replace is not working though

```
 .pipe(cssFilter.restore)
 .pipe($.replace('../../bower_components/bootstrap/fonts/', '../fonts/'))
```

anything else for proper working ? even all my fonts are being copied to **dist/fonts** folder

**Comment by zymr-keshav** [comment]
thanks @gablabelle ; I have followed your steps but with minimal changes; and now running `gulp serve:dist` also have the fonts and icons  here it is

**bower.json**

```
 "overrides": {
   "font-awesome": {
      "main": [
        "less/font-awesome.less",
        "scss/font-awesome.scss"
      ]
    }
  },
```

 in **build.js**
move down the .replace and add one more line for fontawesome 

```
gulp.task('html', ['inject', 'partials'], function () {
....
.pipe(cssFilter.restore)
    .pipe($.replace('../../bower_components/bootstrap/fonts/', '../fonts/'))
    .pipe($.replace('../../bower_components/fontawesome/fonts/', '../fonts/'))
```

also added **otf** in _gulp.task('font')_

```
gulp.task('fonts', function () {
  return gulp.src($.mainBowerFiles())
    .pipe($.filter('**/*.{otf,eot,svg,ttf,woff,woff2}'))
    .pipe($.flatten())
    .pipe(gulp.dest(path.join(conf.paths.dist, '/fonts/')));
});
```

**Comment by McGiogen** [comment]
Pay attention to FontAwesome folder name: now it is `fontawesome` and not `font-awesome` (with a little dash) as wrote many times in this issue.
