### ISSUE TITLE
Add unminifed build target

### ISSUE THREAD

**Issue by tlvince** [Swiip/generator-gulp-angular#342]
A build target that skips all minification would be useful for debugging.

**Comment by Swiip** [comment]
I'm so feared for such a kind of feature which brings people to use it and never be able to minify after... But I agree it can be useful. The best would have been to have sourcemaps for dist task but the status of that on gulp-useref is not clear.

**Comment by zckrs** [comment]
This issue is a nice feature/enhancement but we (Swiip and me) don't have time to implement this for the moment.
Our first priority is stabilized functionality already present in the generator for the purpose of releasing v1.0.0

For clarity in issues I will close the issue.
Any good contributions to resolve this matter is appreciated and merged.
