### ISSUE TITLE
karma configuration file doesn't define Traeur preprocessor

### ISSUE THREAD

**Issue by gt-tech** [Swiip/generator-gulp-angular#360]
When project is using ES6 and Traceur as transpiler, the created project is missing following dev deps:

1. 'karma-traceur-preprocessor',
2. 'karma-requirejs'

Configuration file is missing Traceur pre-processor settings, something on the lines of -

traceurPreprocessor: {
	  options: {
	    sourceMaps: false,
	    modules: 'amd',
	    typeAssertions: false,
	    types: true,
	    annotations: true,
	    typeAssertionModule: 'assert',
	    experimental: true
	  }
    },

 preprocessors: {
      'src/app/**/*.js' : ['traceur'],
      'src/components/**/*.js': ['traceur']
    },

Still struggling with variety of errors after these, it initially seems like karma isn't able to find any tests to run and exits out with code 1, manually modifying testFiles location in unit-tests.js to have .tmp/traceur/**/*.js helps going beyond that problem but still getting a bunch of 404 from web server for partials.

Has anyone tested successfully for unit tests where one unit test does import modules from other app scripts, like importing a DTO or something ...?

**Comment by tyagig** [comment]
Made some progress, traceur bu default use "amd" modules, so i had to add "requirejs". Since requirejs works asynchronously I used the standard test-main.js usual practice as listed here - http://karma-runner.github.io/0.10/plus/requirejs.html. If not done so, browser just hungs on "executing".

After all this, getting below error -
 Uncaught Error: Mismatched anonymous define() module: function () {
       return _;
     }
 http://requirejs.org/docs/errors.html#mismatch
 at C:/Users/gtyagi1/Documents/javascript-workspaces/Temp/test-karma/node_modules/requirejs/require.js:141


EBUG [karma]: Run complete, exiting.
EBUG [launcher]: Disconnecting all browsers
EBUG [launcher]: Process Chrome exited with code 0


I think I know the reason for the error, other libraries have directly been served to browser instead of requirejs loading them. Not yet sure how to fix this since am new to this. Does anyone have any idea/pointers? 

Why this is an issue - we can't run our tests (unit) without this as some of our tests does have "import" statements so need transpiling before they can be executed.

btw below are the project details (I am reproducing and trying to fix this in a separate smaller project) -
====.yo-rc.json ======
{
  "generator-gulp-angular": {
    "props": {
      "paths": {
        "src": "src",
        "dist": "dist",
        "e2e": "e2e",
        "tmp": ".tmp"
      },
      "angularVersion": "~1.3.4",
      "angularModules": [
        {
          "name": "angular-animate",
          "module": "ngAnimate"
        },
        {
          "name": "angular-cookies",
          "module": "ngCookies"
        },
        {
          "name": "angular-touch",
          "module": "ngTouch"
        },
        {
          "name": "angular-sanitize",
          "module": "ngSanitize"
        }
      ],
      "jQuery": {
        "name": "jquery",
        "version": "~2.1.1"
      },
      "resource": {
        "name": "restangular",
        "version": "~1.4.0",
        "module": "restangular"
      },
      "router": {
        "name": "angular-ui-router",
        "version": "~0.2.13",
        "module": "ui.router"
      },
      "ui": {
        "name": "bootstrap-sass-official",
        "version": "~3.3.1",
        "key": "bootstrap",
        "module": null
      },
      "bootstrapComponents": {
        "name": null,
        "version": null,
        "key": "official",
        "module": null
      },
      "cssPreprocessor": {
        "key": "less",
        "extension": "less",
        "module": "gulp-less",
        "version": "~1.3.6"
      },
      "jsPreprocessor": {
        "key": "traceur",
        "extension": "js",
        "srcExtension": "es6",
        "module": "gulp-traceur",
        "version": "~0.14.1"
      },
      "htmlPreprocessor": {
        "key": "none",
        "extension": "html",
        "module": null,
        "version": null
      },
      "foundationComponents": {
        "name": null,
        "version": null,
        "key": null,
        "module": null
      }
    }
  }
}


==== test-main.js (kept in the root directory) ====
var allTestFiles = [];
var TEST_REGEXP = /(spec|test)\.js$/i;

var pathToModule = function(path) {
  return path.replace(/^\/base\//, '').replace(/\.js$/, '');
};

Object.keys(window.__karma__.files).forEach(function(file) {
  if (TEST_REGEXP.test(file)) {
    // Normalize paths to RequireJS module names.
    allTestFiles.push(pathToModule(file));
  }
});

require.config({
  // Karma serves files under /base, which is the basePath from your config file
  baseUrl: '/base',

  // dynamically load all test files
  deps: allTestFiles,

  // we have to kickoff jasmine, as it is asynchronous
  callback: window.__karma__.start
});

=======  Modified testFiles variable in unit-tests.js ....
var testFiles = bowerDeps.js.concat([
    'test-main.js',
    paths.tmp + '/serve/app/index.js',
    paths.src + '/{app,components}/**/*.spec.js',
    paths.src + '/{app,components}/**/*.mock.js'
  ]);

It really isn't an artifact of any specific thing in test/spec file, i removed the file but still get the error so obviously "requirejs" blowing up.

Very well aware that it's not really this generator's problem but perhaps someone who has tried to use this generator might have run into this and can help?

**Comment by gt-tech** [comment]
closing the issue as it's described wrong here. but perhaps yes, adding pre-processors to karma file as per the choices made at the time of project creation might be a good idea to consider.
