### ISSUE TITLE
Custom URL when running gulp serve

### ISSUE THREAD

**Issue by Tuxity** [Swiip/generator-gulp-angular#427]
Hello,

I would like to kown if it's possible to load a custom url than http://localhost:3000 when we run gulp serve ?

Thanks ! Great tool :)

**Comment by fubu** [comment]
You can pass any of the [BrowserSync options]() into the [`browserSync.init`](https://github.com/Swiip/generator-gulp-angular/blob/master/app/templates/gulp/_server.js#L36-L45) call.

I for example changed the task to set the [port](http://www.browsersync.io/docs/options/#option-port) option (depending on an environment var), so that I can run multiple instances in parallel.

That should be enough for your needs I think?

**Comment by Tuxity** [comment]
Hmmm yeah I saw that but with `server` ( http://www.browsersync.io/docs/options/#option-server ) I think I can't change the url. Should I use `proxy` option ?

Thx for the help !

**Comment by fubu** [comment]
What exactly are you trying to achieve? How do you want your URL to look like in the end?

**Comment by Tuxity** [comment]
Yep I want a custom url, not a custom port. Like `subdomain.mydomain.dev`

**Comment by fubu** [comment]
BrowserSync has the concept of "local" and "external" URLs when serving the content. You can specify with the [`open` option](http://www.browsersync.io/docs/options/#option-open) which one to use when opening in the browser. The default is `local`, but you might want `external` together with setting a custom [`host`](http://www.browsersync.io/docs/options/#option-host) (which only applies to the external URL).

**Comment by Tuxity** [comment]
Perfect ! It works ! Thank you :)
