### ISSUE TITLE
Is it safe to update the gulp-angular generator on a live project?

### ISSUE THREAD

**Issue by ajkan** [Swiip/generator-gulp-angular#479]
I am a newbie to using yeoman generators and had a question regarding updating the generator on a live project.

As an example, I am using the 0.9.1 version of the generator-gulp-angular and my project is halfway through development. The latest version seems to be v0.11.0. I see that yeoman has an option to update generators. Would using that option on my present project be safe??

**Comment by Swiip** [comment]
To be perfectly honest: not really. Technically yes, because Yeoman will ask before modifying any file you have but it's difficult to choose where you have made changes and where you want to takes evolutions.

Git can help you rollback some changes or you could even put the new files in a branch and use a git merge to evaluate all changes. There is a better explanation of the process somewhere in the issues but I failed to find it.

**Comment by ajkan** [comment]
@Swiip  np...Thanks for the reply though.
I was just curious about it since the newer version looks a lot more stable.
