### ISSUE TITLE
Reuse bootstrap vars/mixins

### ISSUE THREAD

**Issue by Badisi** [Swiip/generator-gulp-angular#496]
When choosing the bootstrap option from the generator :
- the **vendor.(css|less|scss)** will take care of bootstrap itself.
- the **index.(css|less|scss)** will take care of the application styles.

The problem here, is that we cannot use any bootstrap vars or mixins within the index.(less|scss), or any other (less|scss) that would be injected in it, as bootstrap is not known.

Adding the following in the index.(less|scss) works:
`@import '../../bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap';`
but then bootstrap will be embebbed twice (once in the index.css and once  in the vendor.css)

Any advices or thoughts on that point ?

Thanks!

**Comment by vbud** [comment]
I have ran into this same issue, and I've solved it a couple different ways.

After generating the project, I usually merge vendor.scss into index.scss so that I have access to the variables and mixins of all the SASS dependencies.

The other options would be to import just Bootstrap's variables.scss file into your index.(less|scss).

For bootstrap (less):
`@import '../../bower_components/bootstrap/less/variables.less';`

For bootstrap-sass:
`@import '../../bower_components/bootstrap-sass/assets/stylesheets/bootstrap/variables';`

Then you wouldn't be double-importing the entire framework.

**Comment by jbaroudi** [comment]
Hi @vbud, i change my index.scss it to import variables.scss inside bootstrap

`@import '../../bower_components/bootstrap-sass/assets/stylesheets/bootstrap/variables';` 

at the beggining of my file, but i'm getting the error with gulp build && serve 

**Error: source string:1: error: file to import not found or unreadable: '../../bower_components/bootstrap-sass/assets/stylesheets/bootstrap/variables'**

i have already do "gulp clean", but still getting error... any thoughts why?

**Comment by vbud** [comment]
That's odd. Have you changed the directory structure at all? It seems like it just isn't finding the file.

**Comment by barretodavid** [comment]
@vbud how do you merge vendor.scss into index.scss?

**Comment by vbud** [comment]
Merging them requires changes to `index.scss`, `gulp/styles.js`, and `index.html`. `vendor.scss` can be deleted afterward. At least for bootstrap-sass, the changes to those files look like this:

`index.scss`: Pull in scss from vendor.scss.
```sass
//===== Dependencies SCSS
$icon-font-path: "../../bower_components/bootstrap-sass/assets/fonts/bootstrap/";
// bower:scss
// endbower

//===== Application SCSS partials
// injector
// endinjector
```

`gulp/styles.js`: Change the styles task.
```javascript
gulp.task('styles', function () {
    var sassOptions = {
      style: 'expanded'
    };

    var injectFiles = gulp.src([
      options.src + '/app/**/*.scss',
      '!' + options.src + '/app/index.scss'
    ], { read: false });

    var injectOptions = {
      transform: function(filePath) {
        filePath = filePath.replace(options.src + '/app/', '');
        return '@import \'' + filePath + '\';';
      },
      starttag: '// injector',
      endtag: '// endinjector',
      addRootSlash: false
    };

    return gulp.src([
      options.src + '/app/index.scss'
    ])
      .pipe($.inject(injectFiles, injectOptions))
      .pipe(wiredep(options.wiredep))
      .pipe($.sourcemaps.init())
      .pipe($.sass(sassOptions)).on('error', options.errorHandler('Sass'))
      .pipe($.autoprefixer()).on('error', options.errorHandler('Autoprefixer'))
      .pipe($.sourcemaps.write())
      .pipe(gulp.dest(options.tmp + '/serve/app/'))
      .pipe(browserSync.reload({ stream: true }));
  });
```

`index.html`: Merge the bower build block into the app.css build block. Then delete the vendor.css build block.
```html
<!-- build:css({.tmp/serve,src}) styles/app.css -->
<!-- bower:css -->
<!-- run `gulp inject` to automatically populate bower styles dependencies -->
<!-- endbower -->
<!-- inject:css -->
<!-- css files will be automatically insert here -->
<!-- endinject -->
<!-- endbuild -->
```

**Comment by barretodavid** [comment]
@vbud I have applied your solution but now I'm getting the following error on the console

    Failed to load resource: the server responded with a status of 404 (Not Found)
    http://localhost:3000/bower_components/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.woff2

**Comment by barretodavid** [comment]
@vbud now I know what went wrong. The `$icon-font-path` that you provided in your example is not the same found in the latest versions of the generator that uses `bootstrap-sass-official` instead of just `bootstrap-sass`. The `index.scss` should be:

```sass
//===== Dependencies SCSS
$icon-font-path: "../../bower_components/bootstrap-sass-official/assets/fonts/bootstrap/";
// bower:scss
// endbower

//===== Application SCSS partials
// injector
// endinjector
```

Also, the line 13 of `gulp/inject.js` should be deleted as well:

```javascript
module.exports = function(options) {
  gulp.task('inject', ['scripts', 'styles'], function () {
    var injectStyles = gulp.src([
      options.tmp + '/serve/app/**/*.css'
    ], { read: false });

    var injectScripts = gulp.src([
      options.src + '/app/**/*.js',
      '!' + options.src + '/app/**/*.spec.js',
      '!' + options.src + '/app/**/*.mock.js'
    ])
    .pipe($.angularFilesort()).on('error', options.errorHandler('AngularFilesort'));

    var injectOptions = {
      ignorePath: [options.src, options.tmp + '/serve'],
      addRootSlash: false
    };

    return gulp.src(options.src + '/*.html')
      .pipe($.inject(injectStyles, injectOptions))
      .pipe($.inject(injectScripts, injectOptions))
      .pipe(wiredep(options.wiredep))
      .pipe(gulp.dest(options.tmp + '/serve'));

  });
};
```

Thanks a lot for your help @vbud.

**Comment by vbud** [comment]
Glad you were able to get it working!

**Comment by barretodavid** [comment]
Just in case someone is interested in how this generator handles sass and why we have to do such changes to correctly use bootstrap-sass with our own styles, I created a blog post explaining all [here](http://david-barreto.com/improving-the-yeoman-generator-gulp-angular-sass/). I have also uploaded to my [github account](https://github.com/barretodavid/angular-bootstrap-seed) the modified files ready to be used.

**Comment by zckrs** [comment]
@barretodavid can you create a PR ?

**Comment by barretodavid** [comment]
@zckrs I could try, it would be my first PR ever

**Comment by Swiip** [comment]
We talked about it with @zckrs. Splitting sources and vendors styles started from a good intention but this problem you describe makes it impossible.

We'll merge the two files soon, if we have a PR to help us, it would be perfect.

**Comment by Kageetai** [comment]
Hi there,
I just started trying out your nice generator, but have one little issue now. Whenever starting a new project with Bootstrap, I always use the `variables.less` file to modify the Bootstrap variables, so I would just copy it to the `/app` directory to have it injected automatically, but it's not getting injected and even if I write the import statement manually, the values from `variables.less` do not get applied.
Any idea there?

**Comment by Kageetai** [comment]
Okay, I kinda figured it out myself just now, by following @barretodavid 's link and just merging `vendor.less` and `index.less` into one file. It wasn't even necessary to use another injector, because I just have the one file.
But I still don't seem to understand where the injector injects the files. I just can't see any files injected in ìndex.less`

**Comment by barretodavid** [comment]
@Kageetai the idea of using another injector is to guarantee that any other library that you install using bower and that has a .sass gets also injected, not only bootstrap. I don't know exactly how your project works using less, but I assume it's pretty similar. You can't see the "injected" files (the import statements) because the files are getting compiled and in the process they get also concatenated.

**Comment by Kageetai** [comment]
I am still keeping the `bower:less` comments to inject into the `index.less`. Shouldn't any other library get injected there too?
Just like this:
````
/* Do not remove this comments bellow. It's the markers used by wiredep to inject
   less dependencies when defined in the bower.json of your dependencies */
// bower:less
// endbower

@icon-font-path: '../../bower_components/bootstrap/fonts/';


.browsehappy {
  margin: 0.2em 0;
  background: #ccc;
  color: #000;
  padding: 0.2em 0;
}

.thumbnail {
  height: 200px;

  img.pull-right {
    width: 50px;
  }
}

/* Do not remove this comments bellow. It's the markers used by gulp-inject to inject
   all your less files automatically */
// injector
// endinjector
````

But unfortunately now I noticed the icon fonth path doesn't seem to work anymore...

**Comment by barretodavid** [comment]
@Kageetai only the libraries that defines a .less files in their own bower.json declaration are going to be injected there. The other .css files of those libraries go to a different file called "vendor.css" because they don't need to be compiled. I don't know why your fonts are not being loaded. Are you sure the package is only called "bootstrap" and not something like "bootstrap-less"? It seems to me that you are using the standard bootstrap distribution which only have css files and not less files. I'm just guessing...

**Comment by Kageetai** [comment]
Okay, I overlooked that the `@icon-font-path` gets overriden in `variables.less` again. My mistake :)

And the standard bootstrap distribution is coming with less files by the way...
I noticed the `<link rel="stylesheet" href="app/vendor.css">` in `index.html` Do you mean vanilla css gets injected there? For now I only get an error because that file can't be found, I guess because I don't have any other libraries so far.

**Comment by barretodavid** [comment]
@Kageetai did you delete the file "vendor.less"? You should also delete your ".tmp" an "dist" folders to make sure you are not using some old code that doesn't apply anymore.

**Comment by Kageetai** [comment]
@barretodavid  Yes, and the line in `index.html` mentioned was there from the beginning just after running the generator. I guess it was supposed to go along with the `vendor.less`, but now that that's removed it needs to be removed too, right?

**Comment by barretodavid** [comment]
@Kageetai yes you can delete that line in index.html

**Comment by barretodavid** [comment]
@Kageetai just to be clear: `app/vendor.css` is where `app/vendor.less` file is compiled whereas `styles/vendor.css` is where all the vanilla css files from your libraries are concatenated.

**Comment by Kageetai** [comment]
@barretodavid Okay, thanks, that really helps understanding. One more question though: Will that line reappear if I might have any vanilly CSS in any library in the future?

**Comment by barretodavid** [comment]
@Kageetai no, that line is "hardwired" to the file, it's not something gulp is creating. Once you delete it, it will never bother you again. When you install a library with vanilla css code and run `gulp serve`, a new `index.html` will get created inside the `.tmp` folder, and in that file you will see a slightly different `link` tag with something like `<link rel="stylesheet" href="styles/vendor.css">`. Notice that this is a **different** `vendor.css` file that the one is causing you problem.

**Comment by Kageetai** [comment]
@barretodavid Okay, maybe it would be good to mention that in your article then too, for other newbies like me :)

**Comment by barretodavid** [comment]
@Kageetai you're right, it's something worth mentioning. I'll update the post.

**Comment by zckrs** [comment]
Fixed by https://github.com/Swiip/generator-gulp-angular/pull/596
