### ISSUE TITLE
Foundation Apps inclusion

### ISSUE THREAD

**Issue by AdamJessop** [Swiip/generator-gulp-angular#523]
Hi, 

This is by far my favourite web project starter. I have started looking into foundation for apps: http://foundation.zurb.com/apps

It looks like a nice framework but could definately benefit from the rest of the features of this generator. 

Please accept this as a request to get it integrated :)

**Comment by Swiip** [comment]
We have a hard time maintaining all the options we have already. It's not likely that we add more anytime soon sorry.

But I agree foudation apps seems interesting. If the interest continues growing, it can be possible one day.

**Comment by frankradocaj** [comment]
+1 for foundation apps

Foundation 5 has splintered into Foundation for Websites and Foundation for Apps (SPA).

**Comment by zckrs** [comment]
This issue is a nice feature/enhancement but we (Swiip and me) don't have time to implement this for the moment.
Our first priority is stabilized functionality already present in the generator for the purpose of releasing v1.0.0

For clarity in issues I will close the issue and marks it as "good-but-no-time".
Any good contributions to resolve this matter is appreciated and merged.

Otherwise we will reopen the issue after the v1.0.0
