### ISSUE TITLE
sub-generator for making components and/or routes?

### ISSUE THREAD

**Issue by erikdonohoo** [Swiip/generator-gulp-angular#532]
Your generator is great!  Would you be against a merge request that adds a sub-generator for making components/nested modules?  This would eliminate probably the biggest issue with this generator when it comes to the boilerplate left for end users when making their apps.  I have already done this in my generator, [generator-ng-gulp](https://github.com/erikdonohoo/generator-ng-gulp), and would be happy to make a PR here with the feature if you think it would be something you are interested in.

My idea would be like this:

`yo generator-gulp:[component/module] <path-for-component>`

The path would look something like `/core/friend` or whatever.  The final part of the relative path would be the component name.

You would then get a prompt for various different angular file types (controller, directive, filter, etc.).  You could use any combination of them, and it would create the correct file structure and add the files to the right places and get them on the index.html or whatever.  Similar to what the original angular generator does, but with john papas style guide in mind with nested component based folders.

I would be happy to contribute and submit a PR if you think it sounds like a good idea.

**Comment by gryftir** [comment]
I'd love this feature.

I would suggest that indicating the type (directive, filter, etc) is more likely to be useful then specifying both the component/module and a path, and it allows stubs for testing files to be generated automatically. I'd suggest that the path should be handled automatically unless the user wishes to specify it (maybe have a -p flag for path).

**Comment by Swiip** [comment]
Hello,

First of all, this the older issue of the project: #9. But I'll try to answer here anyway.

I know it's a loved feature in yeoman generators, it's not "my" priority as I wanted most of all a seed project but as this part is nearly secured, we'll soon or later address sub generators.

Right now, we're focused on releasing the 1.0 without adding new important features. So we can't working on this right now. But through #493 which is planned for the 1.0, we start illustrating an angular component of each kind which is a sort of preparation for this feature.

We can imagine starting right now a branch preparing this knowing that this will not be merged before the 1.0 but I want to be clear that this not trivial. Each component generated has to be implemented in 4 languages (JS, ES6, Coffee and TS), has to follow all angular guidelines in code and file structures. The subgenerators has to be designed globally, not one at a time. And finally they must have the same test coverage as the rest of the project. (Sorry to be rude but we already had a PR which didn't follow any of these rules)

For an hint of how to do it, I think many intel on the project choices has to be found in the .yo-rc of the project instead of having to specify the language and the paths at each commands.

Thanks for the contribution offer, if I don't scared you too much, don't hesitate to submit some code and I will open a "sub-generator" branch.

**Comment by erikdonohoo** [comment]
I fully intend to make it keep up the test coverage, handle the various pre-processed languages and make it one global sub-generator.  Much the way I did already in my repo.  (granted I haven't tested everything yet, or supported the different language flavors you have).

I suggested determining the path, mainly because when making a component, you may need more than just one (directive & filter, etc).  The term "component" is very nebulous anyway and could mean any number of things.  The idea with the John Papa style guide is to simply organize your code by feature.  And that can be done a number of ways.

As far as you "scaring" me, rest assured I am not scared.  I appreciate your feedback though, and that helps me to have an idea of what you would expect with such a request.  I would love to help plan and build this with you if you would like any help.

**Comment by zckrs** [comment]
Duplicate https://github.com/Swiip/generator-gulp-angular/issues/9

**Comment by Swiip** [comment]
Ok, happy to see that I didn't scared you :) As I said, we want to secure the 1.0 first but I'll start a new branch against you'll be able to make you PRs.

About the design questions, I didn't think of this enough to have an interesting idea on this. I'll look at it when I can.

**Comment by deebloo** [comment]
when beginning work on this can I also suggest the ability for users to override the templates? that way if someone wants to use controllerAs for example they can just override and modify the templates.

**Comment by erikdonohoo** [comment]
That would make testing the generator more difficult for sure

**Comment by deebloo** [comment]
true. but as long as the generators defined in core are tested it is up to the end users to make sure their templates are written correctly as long as we tell them how to structure them. So in my example I created a generator to create one of those templates for you and then all you have to do is edit it. It isn't the cleanest but it I am kind of in love with the idea. Ember CLI does something similar but they go further while I am just talking about templates. I am sure we could come up with a way to test local templates as well. At the end of the day it is still testing to make sure that the correct files have been created in the correct place.

**Comment by deebloo** [comment]
and please tell me if I am just insane. but being able to have different templates without changes to the core generator is really appealing to me.

**Comment by gryftir** [comment]
Danny,

I worry about too much feature creep; I think it would be better to solve
the issue of component/route generation, which already looks like it will
be challenging if it's part of gulp-angular, and then refactor and enhance
as needed to add more complex user-defined templates.

That said, it occurs to me that component and route generation, or rather
multiple component and route generators (based on language, how templating
works, whatever) could be their own projects and be decoupled from the
surrounding app/project generator.  If somebody wanted to have one that had
super simple hardcoded immutable templates, that wouldn't prevent someone
else from having one with the ability to specify template files.

I figure you could generate gulp-angular then generate the component/route
framework of your choice in the same directory separately.  If Matthieu
felt they were of sufficient quality (I agree with him that what he wants
is non trivial, but it's achievable), they could eventually be included as
options in gulp-angular directly, and have an interface that makes them
easy for gulp-angular and other frameworks to incorporate into the overall
framework install process.  If only some of them were up to snuff for
gulp-angular, that would be okay, you would still have the option to
install them.

So what I'm suggesting is that it might be better to build into
gulp-angular the ability to use component/route generation frameworks
generically, or maybe make no changes at all for the moment.

Or if Erik is mostly done we can just say to hell with greater abstraction
for the moment.







About Me: http://about.me/lawrencesiebert
Constantly Coding: http://constantcoding.blogspot.com

**Comment by deebloo** [comment]
So is what you are saying is to let gulp angular provide the scaffolding while another generator provided the actual sub generators? (route/controller/etc) I do understand scope creep so I think that would make sense.I do know have stopped using sub generators for various projects because I don't like the style of code they generate. So perhaps you are correct and having something like that decoupled from the core app generator is the best way to go. I actually think it would be best to be a part of yeoman proper so no one had to worry about it. Totally understand if this isn't something worth pursuing for this project but thought it was at least worth putting out there. Still my single favorite feature of EmberCli and would like to se something like it outside of the generator that pretty much just I use.

**Comment by deebloo** [comment]
@gryftir and there is nothing keeping me from using this for my project scaffolding and using a separate generator for the other stuff. so the focus may be best separated out. hmmmmmm

**Comment by erikdonohoo** [comment]
Maybe @gryftir is right and all this should just be a separate generator that just plays nice with gulp-angular.  Then @Swiip doesn't have to worry about it but there can still be nice component/route generator generators that are compatible with `gulp-angular`.  Might be the better route.

**Comment by deebloo** [comment]
It certainly maintains a separation of concerns.

**Comment by zckrs** [comment]
One thread for one issue.

Please continue in https://github.com/Swiip/generator-gulp-angular/issues/9#issuecomment-103876166
