### ISSUE TITLE
tsd.json file is not generated

### ISSUE THREAD

**Issue by rogerkerse** [Swiip/generator-gulp-angular#534]
Hi, when I generated new project and uploaded it via git, my friend couldn't get it working, because tsd.json was in gitignore and 'gulp serve' doesn't generate it if it is missing. It just says:

'tsd:install' errored after 480 ms
[00:14:06] VError: cannot locate file /Users/xxx/Documents/myApp/tsd.json

Tried the same thing on my machine, just deleted tsd.json file and same error.

**Comment by mikesigs** [comment]
A temporary fix to this (because it seems like you shouldn't need to do this) is the following:
Run the following command: `node_modules\.bin\tsd init`

Then delete the typings folder it creates in the root of your app, then update bundle property in the tsd.json file to be `"bundle": ".tmp/typings/tsd.d.ts"`

**Comment by mikesigs** [comment]
A good question is, why do we ignore the tsd.json file? Shouldn't it be added to source control, much like the packages.json, bower.json, etc? If you manually install tsd files, they get included in this file. That is valuable information for others who get your code.

**Comment by Swiip** [comment]
I think that this files was "initially" generated and know, it's shiped by the generator so seems that the ignore line should be removed...
