### ISSUE TITLE
Adding support for browserify

### ISSUE THREAD

**Issue by nelsonomuto** [Swiip/generator-gulp-angular#55]

**Comment by zckrs** [comment]
This issue is a nice feature/enhancement but we (Swiip and me) don't have time to implement this for the moment.
Our first priority is stabilized functionality already present in the generator for the purpose of releasing v1.0.0

For clarity in issues I marks it as "good-but-no-time".
Any good contributions to resolve this matter is appreciated and merged.

Otherwise we will reopen the issue after the v1.0.0

**Comment by TJKoury** [comment]
I'm using browserify, and browserify-shim makes sure that I can 'require' anything that's installed via bower.  Works for now.

**Comment by zckrs** [comment]
@Swiip outdated issue ? 
We will use Webpack.

**Comment by Swiip** [comment]
I'm interested but I'm certainly not ready to remove webpack. So it would be an option switching webpack or browserify but definitely not in a close future. I think the tag "good-but-no-time" is appropriated.
