### ISSUE TITLE
Components should not be inside app

### ISSUE THREAD

**Issue by jamm** [Swiip/generator-gulp-angular#559]
In last versions of this generator "components" folder is inside "app" folder.
It's AWFUL. Tremendously awful. I can't live with it.
Inside app each folder is name of route/page, and "components" looks like another page and not like separate folder for code reuse, where code should not be coupled to existing app (not in single line!).

**Comment by zckrs** [comment]
We have already discuss about this subject https://github.com/Swiip/generator-gulp-angular/issues/272

If you can't live with it you can:
* create a PR to offer a option `component-path` https://github.com/Swiip/generator-gulp-angular/blob/master/app/options.json
* revert this PR https://github.com/Swiip/generator-gulp-angular/pull/447 in your local generator

I advise you to read:
* https://google-styleguide.googlecode.com/svn/trunk/angularjs-google-style.html
* https://docs.google.com/document/d/1XXMvReO8-Awi1EZXAXS4PzDzdNvV6pGcuaF4Q9821Es/pub
* https://github.com/johnpapa/angular-styleguide#folders-by-feature-structure

**Comment by jamm** [comment]
I will talk to John and will recommend him move "components" on the same level with "app", but I will not create PR as I see you and Swiip will not merge it anyway (it's opinionated thing and I read your opinions in that awful PR).

**Comment by zckrs** [comment]
What do you mean by "reusable components" ? Between applications ? Between angular module ? 
Inside the application feature store in "components" can be reuse in every page. 
Outside the application you can copy/paste your components. 

Perfect folder structure is utopia. We can't support every usage favorites so we follow good pratices. 

Instead of complaining on all issues dealing with the folder structure, you can create a solution to resolve it (like a option `component-path`).

Last point this repository is a generator not a **framework**. 
You must fork the generator or adapt the sample app.

**Comment by Swiip** [comment]
@jamm, you understand the components folder as a "very generic reusable component" folder. It's not obvious that this was the primary goal.

There is clearly no perfect answers of the app and component folders position. We, as a generator chose one thing and will stick to that because the other way are as questionable as this one.

As @zckrs said, always keep in mind that this is a generator, not a framework, we give what we think is the best start but there a million way a project as specific needs which are not covered. It's why we have to keep it small and users to keep modify it.

**Comment by jamm** [comment]
I don't think I **must** to do anything, @zvkrs. 
I **can** just fork this repo and rollback undesirable changes, change name and work with it as with new project.
Answer to your question: between apps. I thought it's obvious when we talk about code reuse. Your idea about using copy-past as kind of code-reuse I will treat like a joke, it can't be serious.

You had perfect structure and lost it.
As you don't understand my reasoning and choose to stick with this ugly structure, I close issue. Farewell.

**Comment by zckrs** [comment]
Thank you for the constructive issue.
