### ISSUE TITLE
Support for VS2015

### ISSUE THREAD

**Issue by rosieks** [Swiip/generator-gulp-angular#603]
It would be nice if that generator could create project that works with VS2015. I thinking about:
* generating project.json
* copying all sources to wwwroot (or any other specified by user in project.json)
* watch copying all files to wwwroot
* support for running that by IIS/IIS Express instead of node.js

**Comment by Swiip** [comment]
I don't have a windows to test and even less VS so the feature will not come from me.

About a contribution, adding an optionnal project.json to help people with VS why not but I don't want a change of folder structure or an important tweak in the build process because we'll not be able to maintain it.

But seriously, using IIS instead of BrowserSync and lose all its features?

**Comment by zckrs** [comment]
This repository will not support Visual Studio. Sorry =\
