### ISSUE TITLE
A way to not flush partials when running gulp build?

### ISSUE THREAD

**Issue by yuanphoon** [Swiip/generator-gulp-angular#619]
Is there a way to leave the files in the dist/app/ folder intact?

For the curious: I have an ng-include which has an expression in it. The expression (and thus the path) changes depending on a number of vars, but it produces a path to which points towards partials in ../app/components/ etc etc.
Of course when these are dynamically chucked in, I get a 404 because no file exists in that folder.

Alternative solutions welcome, but I just know that chucking my partials back into the dist folder will allow them to be called again.

Thanks.

**Comment by zckrs** [comment]
All parials `.html` are load into Angular template cache. I think you can use the service `$templateCache` with your expression.
https://docs.angularjs.org/api/ng/service/$templateCache

**Comment by Swiip** [comment]
Your mechanism as you descibe it should work. The build process gather all `.html` files and preload them in the template cache without caring how they will be consume by the app. In the bundle, you should be able to somehting like `$templateCache.put(<template-relative-path>, <template-content)`. If you can't read because is uglified, just comment the uglified line in the `build.js` file.

**Comment by yuanphoon** [comment]
Ok turns out this is not a problem with this awesome suite, but rather one for template cache.

If the path to include a partial does not match what's in the template cache precisely, then a 404 error is returned. 

So if you put a path such as templateUrl: '../app/partial/header.html'
The result is 404.

If the path is '/app/partial/header.html', then the result is 200 and the header renders.

The src folder of course doesn't care about this as it sees something at destination anyways. 
All about pathing...*sigh*

Thanks for the assists!
