### ISSUE TITLE
Apply gulp-cache and gulp-remember

### ISSUE THREAD

**Issue by nhducit** [Swiip/generator-gulp-angular#624]
I think it will be great if we add gulp-cache and gulp-remember to reduce build process time.

**Comment by Swiip** [comment]
We had gulp-cache at the beginning but it generated lots of problems and bugs. We finaly removed it. Don't know if I want to give it another shot...

**Comment by nhduc296** [comment]
@Swiip 
I really get big trouble with incremental build.
My project have hundreds js file and It's cost me up to 2 minutes to load web page. Root cause: too many requests to get files (> 1000 files)
I have an idea to deal with this problem:
concatenate all third-party librarys to one file (same as gul-angular way)
concatenate js files in the same folder to one js file. only build all file in folder when one file which lie in that folder changed.

Do you have any suggestion for me?

**Comment by zckrs** [comment]
Just to notice  https://github.com/Swiip/generator-gulp-angular/issues/81

The current gulp workflow can be improve. But im afraid to edit. IMO we should wait the gulp4 released

**Comment by robertbaker** [comment]
@zckrs  Gulp4 is almost ready. I already started completely redoing the gulp tasks using gulp 4 and lazy pipes.
