### ISSUE TITLE
Webpack Integration for normal Javascript Project

### ISSUE THREAD

**Issue by langerc** [Swiip/generator-gulp-angular#706]
Webpack is only available for EC6 Projects, any chance you can add it to the setup selections for normal projects too?

**Comment by Swiip** [comment]
Using Webpack for standard project would mean using CommonJS too. It would lead using NPM in place of Bower and changing a lot of things.

I have ideas of a v2 where all of this would be options but it's not for a close future.

**Comment by langerc** [comment]
thanks for the fast response - im just looking to include modules on demand cause my js files are huge now. Any suggestion for a solution i can apply now? browserify? How do you handle these things in your projects.
An example would be a d3 js library or other big libraries that are only required from one module, since its in the bower pipe it will be included in all of them and the startup time of the project is long.

I found some clues that one can use bower with webpack with some downsteps.

**Comment by Swiip** [comment]
You can for example exclude d3 from wiredep and it will be excluded from the index.html. You'll need a script loader then (any micro lib) to load manually d3 when needed.

If you want to load some Angular modules async, take a look at https://oclazyload.readme.io/ which is great.

Unfortunatly removing some files from the index.html will also remove them from the optimization process because it's based on it. You'll need to handle excluded files in another task.

I don't have recipes or a precise idea on how to do it sorry.

**Comment by langerc** [comment]
Thanks again - this was on my list already - i guess i will upgrade to your latest masterpice and add lazy loading with oclazyload for now.
