### ISSUE TITLE
Template files are not handled by karma-ng-html2js-preprocessor when using Jade

### ISSUE THREAD

**Issue by sdornan** [Swiip/generator-gulp-angular#731]
If you generate an app that uses Jade, the default generated configuration for Karma does not correctly handle loading templates into JavaScript. I ended up using https://github.com/chmanie/karma-ng-jade2js-preprocessor in my project, but there's probably an easy way to make karma-ng-html2js-preprocessor compatible with Jade.

**Comment by Swiip** [comment]
Sorry for the delay. I think it should be as easy as searching for html files in the tmp folder which is not done right now. It's a bug, thanks.

**Comment by lunatik-210** [comment]
The  problem is still there.. It works only when I keep .html files along with .jade in the same folder that doesn't make any scenes..

[13:44:48] Using gulpfile ~/projects/myprofile/frontend/gulpfile.js
[13:44:48] Starting 'scripts:test'...
[13:44:50] Time: 2201ms
          Asset     Size  Chunks             Chunk Names
index.module.js  21.9 kB       0  [emitted]  main
[13:44:50] Finished 'scripts:test' after 2.38 s
[13:44:50] Starting 'test'...
PhantomJS 1.9.8 (Linux 0.0.0) directive navbar should be compiled FAILED
	Error: Unexpected request: GET app/components/navbar/navbar.html
	No more request expected
	    at $httpBackend (/home/andrew/projects/myprofile/frontend/bower_components/angular-mocks/angular-mocks.js:1245)
	    at sendReq (/home/andrew/projects/myprofile/frontend/bower_components/angular/angular.js:10515)
	    at /home/andrew/projects/myprofile/frontend/bower_components/angular/angular.js:10221
	    at processQueue (/home/andrew/projects/myprofile/frontend/bower_components/angular/angular.js:14678)
	    at /home/andrew/projects/myprofile/frontend/bower_components/angular/angular.js:14694
	    at /home/andrew/projects/myprofile/frontend/bower_components/angular/angular.js:15922
	    at /home/andrew/projects/myprofile/frontend/bower_components/angular/angular.js:15733
	    at /home/andrew/projects/myprofile/frontend/.tmp/serve/app/index.module.js:9
	    at invoke (/home/andrew/projects/myprofile/frontend/bower_components/angular/angular.js:4476)
	    at workFn (/home/andrew/projects/myprofile/frontend/bower_components/angular-mocks/angular-mocks.js:2438)
	undefined
PhantomJS 1.9.8 (Linux 0.0.0): Executed 14 of 18 (1 FAILED) (0 secs / 0.077 secs

Generated Karma conf looks like that right now:

'use strict';

var path = require('path');
var conf = require('./gulp/conf');

var _ = require('lodash');
var wiredep = require('wiredep');

var pathSrcHtml = [
  path.join(conf.paths.tmp, '/serve/app/**/*.html'),
  path.join(conf.paths.src, '/**/*.html')
];

function listFiles() {
  var wiredepOptions = _.extend({}, conf.wiredep, {
    dependencies: true,
    devDependencies: true
  });

  return wiredep(wiredepOptions).js
    .concat([
      path.join(conf.paths.tmp, '/serve/app/index.module.js'),
    ])
    .concat(pathSrcHtml);
}

module.exports = function(config) {

  var configuration = {
    files: listFiles(),

    singleRun: true,

    autoWatch: false,

    ngHtml2JsPreprocessor: {
      stripPrefix: conf.paths.src + '/',
      moduleName: 'frontend'
    },

    logLevel: 'WARN',

    frameworks: ['jasmine'],

    browsers : ['PhantomJS'],

    plugins : [
      'karma-phantomjs-launcher',
      'karma-coverage',
      'karma-jasmine',
      'karma-ng-html2js-preprocessor'
    ],

    coverageReporter: {
      type : 'html',
      dir : 'coverage/'
    },

    reporters: ['progress']
  };

  // This is the default preprocessors configuration for a usage with Karma cli
  // The coverage preprocessor in added in gulp/unit-test.js only for single tests
  // It was not possible to do it there because karma doesn't let us now if we are
  // running a single test or not
  configuration.preprocessors = {};
  pathSrcHtml.forEach(function(path) {
    configuration.preprocessors[path] = ['ng-html2js'];
  });

  // This block is needed to execute Chrome on Travis
  // If you ever plan to use Chrome and Travis, you can keep it
  // If not, you can safely remove it
  // https://github.com/karma-runner/karma/issues/1144#issuecomment-53633076
  if(configuration.browsers[0] === 'Chrome' && process.env.TRAVIS) {
    configuration.customLaunchers = {
      'chrome-travis-ci': {
        base: 'Chrome',
        flags: ['--no-sandbox']
      }
    };
    configuration.browsers = ['chrome-travis-ci'];
  }

  config.set(configuration);
};
