### ISSUE TITLE
Add angular generators

### ISSUE THREAD

**Issue by asm0dey** [Swiip/generator-gulp-angular#9]
like in default generator:
  angular:constant
  angular:controller
  angular:decorator
  angular:directive
  angular:factory
  angular:filter
  angular:main
  angular:provider
  angular:route
  angular:service
  angular:value
  angular:view

**Comment by gen4sp** [comment]
+1

**Comment by atul-bhosale** [comment]
+1

**Comment by jagwire** [comment]
+1

**Comment by palpalani** [comment]
+1

**Comment by cmcnamara87** [comment]
+1

**Comment by homeway** [comment]
+1

**Comment by doronsever** [comment]
I've created a subtask generator for this purpose. I really hope my project will be merged to this one in the near future. 
https://github.com/doronsever/generator-gulp-angular-subtask
Please read the instruction first

**Comment by zckrs** [comment]
@doronsever nice contribution :smiley: 
I will follow your project and after version 1.0.0 we will integrate your subgenerator with your help I guess
cc @Swiip

**Comment by deebloo** [comment]
when beginning work on this can I also suggest the ability for users to override the templates? that way if someone wants to use controllerAs for example they can just modify the templates.

**Comment by zckrs** [comment]
I suggest to the community to create and share your own subtask. 
Like @doronsever who create https://github.com/doronsever/generator-gulp-angular-subtask you can use composability. http://yeoman.io/authoring/composability.html
***
This issue is a nice feature/enhancement but we (Swiip and me) don't have time to implement this for the moment.
Our first priority is stabilized functionality already present in the generator for the purpose of releasing v1.0.0

For clarity in issues I will close the issue and marks it as "good-but-no-time".
Any good contributions to resolve this matter is appreciated and merged.

Otherwise we will reopen the issue after the v1.0.0

**Comment by deebloo** [comment]
@zckrs apologies for multiple threads :)

**Comment by ksambhav** [comment]
+1

Make life a lot easier while working with a bigger team of varying expertise. Easy to add/remove/move/share modules between multiple apps.

**Comment by brunoksato** [comment]
+1

**Comment by zckrs** [comment]
Closed in favor of https://github.com/Swiip/generator-gulp-angular/issues/793
