### ISSUE TITLE
Executing npm install -g generator-gulp-angular is not installing the generator

### ISSUE THREAD

**Issue by danielrvt** [Swiip/generator-gulp-angular#920]
The generator doesn't seem to exist after installing it following the directions given in the README. After installing it, I executed yo gulp-angular and Yeoman didn't recognised the generator.

Is there something missing?

**Comment by edmanolache** [comment]
I'm having the same issue but It seems like I can't install any yo generator.

**Comment by scttcper** [comment]
Got the same thing. Reverted to previous version: `npm install -g generator-gulp-angular@v1.0.0`

**Comment by krzysieki** [comment]
Same error. 1.0.0 worked, after update to 1.0.1 yeoman does not see generator

**Comment by elboman** [comment]
Argh! It drove me insane the whole day. I was using NVM and I thought it was related to that, but then I tried another generator and there was no problem. Eventually I installed v1.0.0 and it's working fine.

@edmanolache are you using NVM on your computer? Yeoman has problems recognizing generators when using NVM due to the NODE_PATH being empty.

**Comment by danielrvt** [comment]
Thanks guys! It worked using v1.0.0. This should be documented also, since we wasted a lot of time with this issue.

**Comment by busches** [comment]
I'd leave this issue opened, v1.0.1 should show up as a generator option.

**Comment by simonghales** [comment]
+1

**Comment by ansumanshah** [comment]
+1 reopen the issue

**Comment by zckrs** [comment]
Released 1.0.2 who fixed issue
