### ISSUE TITLE
problem to create a factory

### ISSUE THREAD

**Issue by maxmusic** [Swiip/generator-gulp-angular#978]
hi guys! ... i have problem with creating factory, It shows me this error: Cannot call a class as a function...

my code is 
````javascript
// in index.module.js:

// code...
import { LoginController } from './login/loginController';
import { LoginFactory } from './login/login.factory';
// code...

angular.module('myApp', [
// code...
])

// code...
  .factory('LoginFactory', LoginFactory)
  .controller( 'LoginController', LoginController )
//code...


//in login.factory.js

export class LoginFactory {
    constructor(){
        'ngInject';
    }
    return 
}

// in loginController.js

export class LoginController {
   constructor ($scope, LoginFactory) {
     'ngInject';
   }
}
````
I hope you can help... thanks

**Comment by pablorsk** [comment]
Hi @maxmusic, 
```
.factory('LoginFactory', LoginFactory)
```
This does not work, never is instantiated. This is because the function passed as a second argument (LoginFactory) is never called with the new operator. If you want to use a TypeScript class you must use service and not factory.

Via [stackoverflow](http://stackoverflow.com/questions/26112608/inject-a-factory-in-angularjs-using-typescript)
