### ISSUE TITLE
webpack + require

### ISSUE THREAD

**Issue by 0101adm** [Swiip/generator-gulp-angular#998]
once i build my app, i get an error that require cannot be found.  i get this in my browser console...

```
Uncaught ReferenceError: require is not defined(anonymous function) @ app-e328626ca8.js:6
angular.js:12722
```

line 6 is...
```
var index_constant_1=require("./index.constant")
```

the only difference between the last build is i updated angular to 1.4.9.

anyone else getting this?

**Comment by masoapps** [comment]
I also get this error when using serve:dist and when deploying the dist folder to Azure.  The standard serve task works fine though.

**Comment by 0101adm** [comment]
@masoapps i had to redo the project to fix this.

**Comment by bearfriend** [comment]
@0101adm I'm getting this error too. What exactly do you mean by "redo"?

**Comment by 0101adm** [comment]
i fought w/ the issue then decided to nuke the workflow and regen from scratch.  not sure what fixed it.

**Comment by bearfriend** [comment]
I've figured out what the issue was. I use Atom as my editor with the atom-typescript package installed. One of the things this package does is auto-compile to `.js` files on save. On `build`, the project seems to prefer these files over re-compiling the `.ts` files before concatenating. This is where the `require` calls come from. Either disable auto-compiling if you can, delete the `.js` files, or script their removal or overriding.

**Comment by 0101adm** [comment]
:+1:

**Comment by masoapps** [comment]
@bearfriend Thank you for the response - it's helped me fix the issue.  I'm using typescript with Webstorm - it seems the auto-compiled .js files were also causing issues here.  Fortunately didn't need to restart the project

**Comment by bearfriend** [comment]
@masoapps Fantastic. Glad I could help.
